"""empty message

Revision ID: 12a74b8ff9b6
Revises: 27540a843b53
Create Date: 2014-07-23 17:34:20.744034

"""

# revision identifiers, used by Alembic.
revision = '12a74b8ff9b6'
down_revision = '27540a843b53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('rubric_category_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'rubric_category_id')
    ### end Alembic commands ###
