"""empty message

Revision ID: 174d1a0c80f1
Revises: 38d2eb4f1b1b
Create Date: 2014-08-13 16:40:28.305356

"""

# revision identifiers, used by Alembic.
revision = '174d1a0c80f1'
down_revision = '38d2eb4f1b1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "special_program_id_fkey",
        "application_essay_template",
        "special_program",
        ["special_program_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
