"""empty message

Revision ID: 180a22009288
Revises: 595d6dbb11cd
Create Date: 2014-08-01 19:51:01.423004

"""

# revision identifiers, used by Alembic.
revision = '180a22009288'
down_revision = '595d6dbb11cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay', sa.Column('is_displayed', sa.Boolean(), nullable=True))
    op.add_column('theme_essay', sa.Column('is_displayed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme_essay', 'is_displayed')
    op.drop_column('application_essay', 'is_displayed')
    ### end Alembic commands ###
