"""empty message

Revision ID: 18f161cb776e
Revises: 4a1f830bd069
Create Date: 2014-08-13 20:08:46.719762

"""

# revision identifiers, used by Alembic.
revision = '18f161cb776e'
down_revision = '4a1f830bd069'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column


def upgrade():
    connection = op.get_bind()

    application_essay_template = table(
        'application_essay_template', column('use_common_app', sa.Boolean)
    )

    op.execute(
        application_essay_template.update().where(
            application_essay_template.c.use_common_app==None).values({'use_common_app': False}))

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay_template', 'use_common_app',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay_template', 'use_common_app',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
