"""empty message

Revision ID: 1e028e4a140d
Revises: 54302fd68ce7
Create Date: 2014-08-14 18:03:00.416901

"""

# revision identifiers, used by Alembic.
revision = '1e028e4a140d'
down_revision = '54302fd68ce7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay_template', 'choice_group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay_template', sa.Column('choice_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "choice_group_id_id_fkey",
        "essay_template",
        "choice_group",
        ["choice_group_id"], ["id"])
    ### end Alembic commands ###
