"""empty message

Revision ID: 1f4b2391e62f
Revises: 4de3b36e7758
Create Date: 2014-08-14 15:37:02.008870

"""

# revision identifiers, used by Alembic.
revision = '1f4b2391e62f'
down_revision = '4de3b36e7758'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    application_essay = table(
        'application_essay', column('onboarding_is_selected', sa.Boolean)
    )
    op.execute(
        application_essay.update().where(
            application_essay.c.onboarding_is_selected==None).values({'onboarding_is_selected': False}))

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay', 'onboarding_is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay', 'onboarding_is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
