"""empty message

Revision ID: 201927ec0c30
Revises: 3b6928761e16
Create Date: 2014-08-14 22:59:27.631833

"""

# revision identifiers, used by Alembic.
revision = '201927ec0c30'
down_revision = '3b6928761e16'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    application_essay_template = table(
        'application_essay_template', column('requirement_type', sa.VARCHAR())
    )
    op.execute(
        application_essay_template.update().where(
            application_essay_template.c.requirement_type==None).values({'requirement_type': 'Required'}))

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay_template', 'requirement_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default="Required'::character varying")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay_template', 'requirement_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default="Required'::character varying")
    ### end Alembic commands ###
