"""empty message

Revision ID: 22e3d2deab68
Revises: 174d1a0c80f1
Create Date: 2014-08-13 18:01:41.264295

"""

# revision identifiers, used by Alembic.
revision = '22e3d2deab68'
down_revision = '174d1a0c80f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
