"""empty message

Revision ID: 23bc1d99de1
Revises: 12a74b8ff9b6
Create Date: 2014-08-05 12:57:36.530893

"""

# revision identifiers, used by Alembic.
revision = '23bc1d99de1'
down_revision = '12a74b8ff9b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('is_displayed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'is_displayed')
    ### end Alembic commands ###
