"""empty message

Revision ID: 27540a843b53
Revises: 4714084275cf
Create Date: 2014-07-15 12:14:26.110077

"""

# revision identifiers, used by Alembic.
revision = '27540a843b53'
down_revision = '4714084275cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('dom_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'dom_id')
    ### end Alembic commands ###
