"""empty message

Revision ID: 2b64dd55b17a
Revises: 18f161cb776e
Create Date: 2014-08-14 14:44:16.966792

"""

# revision identifiers, used by Alembic.
revision = '2b64dd55b17a'
down_revision = '18f161cb776e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_essay_template', 'use_common_app')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay_template', sa.Column('use_common_app', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
