"""empty message

Revision ID: 2f59d8643b13
Revises: 27540a843b53
Create Date: 2014-07-31 20:04:32.048097

"""

# revision identifiers, used by Alembic.
revision = '2f59d8643b13'
down_revision = '27540a843b53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
