"""empty message

Revision ID: 308be85bb06a
Revises: 4f0a2749186a
Create Date: 2014-08-15 13:24:33.844949

"""

# revision identifiers, used by Alembic.
revision = '308be85bb06a'
down_revision = '4f0a2749186a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_group', sa.Column('cg_id', sa.Integer(), nullable=True))
    op.drop_column('choice_group', 'choice_group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_group', sa.Column('choice_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('choice_group', 'cg_id')
    ### end Alembic commands ###
