"""empty message

Revision ID: 38d2eb4f1b1b
Revises: 445022412fbf
Create Date: 2014-08-13 15:50:17.820439

"""

# revision identifiers, used by Alembic.
revision = '38d2eb4f1b1b'
down_revision = '445022412fbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay_template', sa.Column('special_program_id', sa.Integer, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_essay_template', 'special_program_id')
    ### end Alembic commands ###
