"""empty message

Revision ID: 3ad962e9cab7
Revises: 3c4966b36d6c
Create Date: 2014-08-14 15:11:47.292557

"""

# revision identifiers, used by Alembic.
revision = '3ad962e9cab7'
down_revision = '3c4966b36d6c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    university = table(
        'university', column('use_common_app', sa.Boolean)
    )
    op.execute(
        university.update().where(
            university.c.use_common_app==None).values({'use_common_app': False}))

    user = table(
        'user', column('onboarded', sa.Boolean)
    )
    op.execute(
        user.update().where(
            user.c.onboarded==None).values({'onboarded': False}))


    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('university', 'use_common_app',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('university', 'use_common_app',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
