"""empty message

Revision ID: 3b6928761e16
Revises: 52ed23df5def
Create Date: 2014-08-14 22:56:46.704697

"""

# revision identifiers, used by Alembic.
revision = '3b6928761e16'
down_revision = '52ed23df5def'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_essay_template', 'requirement_type',
               existing_type=sa.VARCHAR(),
               server_default='Required',
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
