"""empty message
 
Revision ID: 445022412fbf
Revises: 21411d1665c3
Create Date: 2014-08-08 02:41:58.520086
 
This was created on the dev heroku instance, copied to local, and used to stab coding gods in the eye.
"""
 
# revision identifiers, used by Alembic.
revision = '445022412fbf'
down_revision = '21411d1665c3'
 
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models.fields import SerializableDateTime
from sqlalchemy import text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay_associations', sa.Column('created_ts', SerializableDateTime, nullable=False, server_default=text('now()')))
    op.add_column('essay_associations', sa.Column('deleted_ts', SerializableDateTime, nullable=True))
    op.add_column('essay_associations', sa.Column('state', sa.String(), nullable=False, server_default="pending"))
    op.add_column('essay_associations', sa.Column('updated_ts', SerializableDateTime, nullable=False, server_default=text('now()')))
    op.alter_column('essay_associations', 'application_essay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('essay_associations', 'theme_essay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tag', 'rubric_category_id')
    op.drop_column('theme_essay', 'application_essay_states')
    ### end Alembic commands ###
 
 
def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_essay', sa.Column('application_essay_states', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('rubric_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('essay_associations', 'theme_essay_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('essay_associations', 'application_essay_id',
               existing_type=sa.INTEGER(),
               nullable=True)