"""empty message

Revision ID: 4714084275cf
Revises: None
Create Date: 2014-07-10 11:26:45.405502

"""

# revision identifiers, used by Alembic.
revision = '4714084275cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
