"""empty message

Revision ID: 4a1f830bd069
Revises: 22e3d2deab68
Create Date: 2014-08-13 20:07:27.692925

"""

# revision identifiers, used by Alembic.
revision = '4a1f830bd069'
down_revision = '22e3d2deab68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay_template', sa.Column('use_common_app', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_essay_template', 'use_common_app')
    ### end Alembic commands ###
