"""empty message

Revision ID: 4cd1075f8040
Revises: 1f4b2391e62f
Create Date: 2014-08-14 17:54:53.300915

"""

# revision identifiers, used by Alembic.
revision = '4cd1075f8040'
down_revision = '1f4b2391e62f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
