"""empty message

Revision ID: 4f0a2749186a
Revises: a6780d5b850
Create Date: 2014-08-14 16:19:55.304418

"""

# revision identifiers, used by Alembic.
revision = '4f0a2749186a'
down_revision = 'a6780d5b850'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_group', sa.Column('university_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice_group', 'university_id')
    ### end Alembic commands ###
