"""empty message

Revision ID: 52ed23df5def
Revises: 9b6f20970df
Create Date: 2014-08-14 22:45:06.609880

"""

# revision identifiers, used by Alembic.
revision = '52ed23df5def'
down_revision = '9b6f20970df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay_template', sa.Column('requirement_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_essay_template', 'requirement_type')
    ### end Alembic commands ###
