"""empty message

Revision ID: 54302fd68ce7
Revises: 4cd1075f8040
Create Date: 2014-08-14 17:56:30.000315

"""

# revision identifiers, used by Alembic.
revision = '54302fd68ce7'
down_revision = '4cd1075f8040'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay_template', sa.Column('choice_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "choice_group_id_id_fkey",
        "essay_template",
        "choice_group",
        ["choice_group_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay_template', 'choice_group_id')
    ### end Alembic commands ###
