"""empty message

Revision ID: 595d6dbb11cd
Revises: 78654962fec
Create Date: 2014-08-01 19:38:00.744030

"""

# revision identifiers, used by Alembic.
revision = '595d6dbb11cd'
down_revision = '27540a843b53'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'is_final_draft')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
   op.add_column('draft', sa.Column('is_final_draft', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
