"""empty message

Revision ID: 9b6f20970df
Revises: 1e028e4a140d
Create Date: 2014-08-14 18:10:29.383228

"""

# revision identifiers, used by Alembic.
revision = '9b6f20970df'
down_revision = '1e028e4a140d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_essay_template', sa.Column('choice_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "choice_group_id_id_fkey",
        "application_essay_template",
        "choice_group",
        ["choice_group_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_essay_template', 'choice_group_id')
    ### end Alembic commands ###
