"""empty message

Revision ID: a6780d5b850
Revises: 201927ec0c30
Create Date: 2014-08-14 16:15:34.859580

"""

# revision identifiers, used by Alembic.
revision = 'a6780d5b850'
down_revision = '201927ec0c30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_group', sa.Column('choice_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice_group', 'choice_group_id')
    ### end Alembic commands ###
